spring:
  application:
    name: core-sim-j
  datasource:
    url: jdbc:postgresql://${PG_HOST:localhost}:5432/vinocore
    username: ${PG_USERNAME:vinocore}
    password: ${PG_PASSWORD:vinocore}
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 10000
      max-lifetime: 600000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true
