spring:
  application:
    name: core-sim-j
  datasource:
    url: jdbc:postgresql://${PG_HOST:localhost}:5432/vinocore
    username: ${PG_USERNAME:vinocore}
    password: ${PG_PASSWORD:vinocore}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true
